apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: building-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    creationTimestamp: null
    labels:
      template: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    resources: {}
    source:
      git:
        uri: ${GIT_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:5.5
          namespace: openshift
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - github:
        secret: OpaYR3Nr4kR3wK2eSiEpx7yppmJk8Sd7hbh4Byme
      type: GitHub
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    creationTimestamp: null
    labels:
      template: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
parameters:
- description: Git project to checkout
  name: GIT_URL
  required: true
  value: https://github.com/openshift/cakephp-ex.git
- description:
  name: APPLICATION_NAME
  required: true
  value: myapp
